### ISSUE TITLE
using old-style `plugins` in config

### ISSUE THREAD

**Issue by bennypowers** [modernweb-dev/rocket#3]
ideally, users should be able to use `config.devServer.plugins` as well as `setupDevPlugins:[addPlugin(...)]`

**Comment by daKmoR** [comment]
as a user you can now set the `config.devServer.plugins`.
However note that it will completely override plugins. (e.g. if you provide plugins then you set all plugins)
Currently that not an issue as there are no default plugins for the devServer yet - the preferred way however is to use `setupDevPlugins`

adding full dev server plugins via `setupDevPlugins` is not supported as those will no longer be auto wrap by `@web/dev-server-rollup`

fixed in https://github.com/modernweb-dev/rocket/pull/5
