### ISSUE TITLE
Encapsulating JS and CSS within a Preset

### ISSUE THREAD

**Issue by gdbaldw** [modernweb-dev/rocket#91]
For JS, I decided to place the script tag in a joiningBlock below my content. But, CSS should be in the head, which it seems is always global and cannot be encapsulated. Am I properly encapsulating JS, and is Rocket's intent that CSS should not be encapsulated?

**Comment by daKmoR** [comment]
I'm not really sure what you mean 🤔

can you provide some code examples and what you would expect to happen?

**Comment by gdbaldw** [comment]
> I'm not really sure what you mean
> 
> can you provide some code examples and what you would expect to happen?

Sure, take the RocketBlog preset as an example. The file at `_includes/_joiningBlocks/head/add-blog-css.njk` is applied to all pages, even though it only useful for `docs/blog`, and could in theory pollute/overwrite styles of other sections.

More troublesome would be unnecessarily importing a large script, e.g. `_includes/_joiningBlocks/bottom/import_large_script.njk`, which is applied to all pages.

As an alternative, I am using `_includes/_joiningBlocks/_layoutMyTemplate/content/30-import_large_script.njk`, containing:

`<script type="module">
    import LargeScript from 'my_npm_module'
</script>`

So, my script is encapsulated to only that one template defined by my preset. But, instead of properly being imported below the footer, my script is imported after my content but above the footer.

So, I am wondering if I am using Rocket as intended, that maybe all scripts and styles are expected to be applied to all pages, that at the bottom of content is the best place for an encapsulated script, and since styles should be in the head, all styles are to be applied to all pages?

**Comment by daKmoR** [comment]
if you have a large script that is only used on a specific page it's fine to put it into the content of the page... especially as the build optimization (rollup) will "process" it anyways...

`type="module"` scripts are always loaded "deferred" so that not an issue either...

if you are using markdown you could use 

````md
```js script
import 'foo';
```
````

as this will place it in a specific file only for this page...

I'm going to close this as it should be fine - if you have additional questions or concerns feel free to reopen or to create a new issue 🤗

**Comment by bennypowers** [comment]
@gdbaldw I'm doing some extensive work on this and hope to publish an examplar soon
